extends:
  - stylelint-config-recommended
  # always put prettier last
  - stylelint-prettier/recommended
plugins:
  - stylelint-prettier
rules:
  prettier/prettier: true
  no-empty-source: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - layer
        - variants
