[build.environment]
  NODE_VERSION = "15.14.0"

[build]
  command = '''
  cd ../.. && \
  node common/scripts/install-run-rush.js install && \
  node common/scripts/install-run-rush.js export --verbose --to napjoseph
  '''
  publish = "out"

[context.production.environment]
  NODE_ENV = "production"
