name: (calub-web) deploy to github pages

on:
  push:
    branches:
      - main
    paths:
      - 'personal/calub/**'

jobs:
  build-and-deploy:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 15.14.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install rush with no-link
        run: node common/scripts/install-run-rush.js install --no-link
      - name: link project
        run: node common/scripts/install-run-rush.js link
      - name: build and export
        run: node common/scripts/install-run-rush.js export --verbose --to calub-web
        env:
          NEXT_PUBLIC_GA_ID: 'G-26QBVG95QT'
          NEXT_PUBLIC_BASEPATH: '/calub'
          NEXT_IMAGES_LOADER: 'imgix'
          NEXT_IMAGES_PATH: '<empty>'
          BROWSERSLIST_IGNORE_OLD_DATA: '1'
      - name: deploy to external repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.PAGE_DEPLOY_KEY }}
          external_repository: napjoseph/calub
          publish_dir: ./personal/calub/out
          publish_branch: export--mono-rush
          keep_files: false
          allow_empty_commit: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
